### ISSUE TITLE
Unexpected string

### ISSUE THREAD

**Issue by nickforddev** [timhuff/babel-alias-quokka-plugin#2]
I'm trying to set this up in a project generated by `@vue/cli` 3.x, which sets up a webpack alias to map `@` to `./src/`. I've installed `babel-alias-quokka-plugin` into `~/.quokka`, and I added the following to package.json in my project: 

```json
"quokka": {
    "babel": true
  },
  "babel": {
    "presets": [
      "@vue/app"
    ]
  }
```
Note that vue cli actually puts the babel config into `babel.config.js` by default, but the docs for quokka only mention `.babelrc`, so I tried adding it to package.json too.

Then if I start quokka I get a complain about `@babel/register` missing, so I installed that into my projects.

Then when I try to start quokka in a file that uses the `@` alias, I get the following error:
```
​​​​Quokka 'utils.spec.js' (node: v11.7.0, babel: v7.2.2)​​​​
 
Unexpected string 
  at ​​​new Script​​​ ​vm.js:84​
  at ​​​createScript​​​ ​vm.js:264​
  at ​​​Object.runInThisContext​​​ ​vm.js:312​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:684​
```

It should be noted that I'm getting this error in a normal js file, not a .vue single file component.

Any help would be greatly appreciated!

**Comment by nickforddev** [comment]
I actually get that error in any js files now, not just files that use the `@` alias

**Comment by smcenlly** [comment]
We tried setting up Quokka to use `@vue/app` preset and had the same problem. The transformed Javascript that Quokka is trying to run uses ES6 modules instead of CommonJS, which node is not going to run in node by default. We identified the cause of the problem using the Quokka command, `Show Instrumented Code` after we got the error.

Normally the way Quokka customers address this issue is with the use of babel transforms that convert from ES6 modules to CommonJS.

We took a look at vue's [babel-preset-app code](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/babel-preset-app/index.js), and it does not convert your ES6 modules to CommonJS unless the environment variable `VUE_CLI_BABEL_TRANSPILE_MODULES` is set.

You will need to do this in your `quokka` configuration. See below for an example that configures Quokka in a package.json. You can read more about how to do this in [Quokka docs](https://quokkajs.com/docs/configuration.html#environment-variables).

```json
"quokka": {
    "env": {
      "params": {
        "env": "VUE_CLI_BABEL_TRANSPILE_MODULES=true"
      }
    },
    "babel": true,
    "plugins": [
      "babel-alias-quokka-plugin"
    ],
    "alias": {
      "test": "./test"
    }
  }
```

We have created a sample repo for you [here](https://github.com/wallabyjs/babel-alias-quokka-plugin-issue-2) that shows Quokka working with the `babel-alias-quokka-plugin`, using the same source files that are specified in the project's README.md.

If you're using a later version of `node`, you may also try [specifying a node flag](https://quokkajs.com/docs/configuration.html#environment-variables#node-flags) to enable [ECMAScript Modules](https://nodejs.org/api/esm.html).

**Comment by nickforddev** [comment]
Awesome that worked! Thank you so much!
